import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header.js";
import { UserProvider } from "@/context/user-provider";
import { AuthProvider } from "@/context/auth-provider";
import { ToastProvider } from "@/context/toast-provider";
import { ToastContainer, Slide } from "react-toastify";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: { default: "Blog App", template: "%s | Blog App" },
    description: "Blog App Generated by create next app",
};

export default function PublicLayout({ children }) {
    return (
        <html lang="en">
            <ToastProvider>
                <AuthProvider>
                    <UserProvider>
                        <body
                            className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
                        >
                            <Header />
                            {children}
                            <Footer />
                            <ToastContainer
                                position="top-right"
                                autoClose={3000}
                                hideProgressBar={false}
                                newestOnTop
                                closeOnClick={false}
                                rtl={false}
                                pauseOnFocusLoss
                                draggable
                                pauseOnHover
                                theme="light"
                                transition={Slide}
                            />
                        </body>
                    </UserProvider>
                </AuthProvider>
            </ToastProvider>
        </html>
    );
}
